version: '3.8'
services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - type: bind
        source: /path/to/local/.gitconfig
        target: /home/ubuntu/.gitconfig
      - type: bind
        source: /path/to/local/.ssh
        target: /home/ubuntu/.ssh
      - type: bind
        source: ./  # This assumes docker-compose is run from the project directory
        target: /app
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

  # Example container with DooD and host file/net access
  app1:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app2}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    
  # Example of running the same image with different intent
  app2:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=${TESTVAR:-app2}
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
